### ISSUE TITLE
Multiple services of type Symfony\Component\EventDispatcher\EventDispatcherInterface found: events.symfonyProxy, 1.eventDispatcher

### ISSUE THREAD

**Issue by jiripudil** [Arachne/EventDispatcher#1]
Although EventDispatcherExtension [removes events.symfonyProxy](https://github.com/Arachne/EventDispatcher/blob/ba5f7e711865388ef9b03a01a0095d25195ca4ab/src/DI/EventDispatcherExtension.php#L40), Kdyby's ConsoleExtension [reaches into the container builder](https://github.com/Kdyby/Console/blob/b6ab544a125aff4880fad82fe19736302d4959a6/src/Kdyby/Console/DI/ConsoleExtension.php#L168) for EventDispatcherInterface in its beforeCompile method which obviously breaks if the EventDispatcherExtension is registered after ConsoleExtension.

I don't think either of the packages has any means to address this issue, except maybe for pointing out somewhere in the docs that this extension should be registered _before_ Kdyby's ConsoleExtension?

**Comment by enumag** [comment]
Yeah. I noticed this issue yesterday too but couldn't find a way to fix it. Adding it do the docs it probably the only thing I can do with it.

**Comment by enumag** [comment]
I've been experimenting a little bit. If I call the removeDefinition for symfonyProxy in both loadConfiguration and beforeCompile the problem disappeared for all cases except for this one:

```
extensions:
    kdyby.console: Kdyby\Console\DI\ConsoleExtension
    arachne.eventdispatcher: Arachne\EventDispatcher\DI\EventDispatcherExtension
    kdyby.events: Kdyby\Events\DI\EventsExtension
```

I don't really expect anyone to mix the extensions like this though. Most people will put Kdyby/Events above Kdyby/Console or at least not put Arachne/EventDispatcher between the two.

What do you think?
